language: node_js
node_js:
  - "node"

before_deploy:
  - gatsby build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gatsby
  local-dir: public
  target-branch: master
