# Site settings
title: Ben Ilegbodu
description: "Christ follower, husband & father of ✌. UI Architect & Speaker. ES6+, React & CSS3. Basketball, DIY & movies. Frontend Platform Manager @ Eventbrite"
url: "http://www.benmvp.com"
paginate: 4
paginate_path: "/page/:num/"


# Build settings
permalink: pretty
gems: [jekyll-paginate, jekyll-redirect-from, jekyll-feed, jekyll-sitemap]
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM

# Site owner
owner:
  name: Ben Ilegbodu
  email: ben@benmvp.com
  disqus-shortname: benmvp
  twitter: benmvp
  github: benmvp
  linkedin: benmvp
  google:
    analytics: UA-65375615-1
