# Site settings
title: Ben Ilegbodu
description: "{priorities:['Christ','Family','Work'], work:'@Eventbrite', title:'Sr UI Engineer', tech:['#ES6,'#CSS3','#HTML5'], passions:['#Jesus','@NBA']}"
url: "https://benmvp.github.io"
paginate: 4
paginate_path: "/page/:num/"


# Build settings
permalink:   pretty
permalink: pretty
gems: [jekyll-paginate, jekyll-redirect-from, jekyll-feed, jekyll-sitemap]
highlighter: pygments
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']

# Site owner
owner:
  name: Ben Ilegbodu
  email: ben@benmvp.com
  disqus-shortname: benmvp
  twitter: benmvp
  github: benmvp
  linkedin: benmvp
  google:
    analytics: UA-65375615-1
