# Site settings
title: Andre Christoga
email: andre.christoga@gmail.com
description: "produk, metode, dan kode"
username: andrechristoga
baseurl: "/blog"
url: "http://christoga.github.io/blog"
paginate: 10
paginate_path: "/halaman/:num/"

# Build settings`
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
highlighter: pygments
